export const UPDATE_GRAPH_SELECTION = "UPDATE_GRAPH_SELECTION";
export const UPDATE_LABEL_SELECTION = "UPDATE_LABEL_SELECTION";
export const UPDATE_CURR_GRAPH_VALUE = "UPDATE_CURR_GRAPH_VALUE";
export const UPDATE_FINAL_GRAPH_VALUE = "UPDATE_FINAL_GRAPH_VALUE";
export const ADD_LABEL_OPTION = "ADD_LABEL_OPTION";
export const UPDATE_PREVIEW = "UPDATE_PREVIEW";